from ..socket_server_lib.constants import Options

class Constants:
    DISCOVER_CAMERA_QUERY_PORT = 5000
    CAMERA_HANDLER_PORT = 5001
    SERVER_COMMS_PORT = 5002

    CAMERA_MAC_PREFIX = b"12:34:56"

class Messages:
    CAMERA_PAIRING_QUERY = [b"CAMPAIR-HSEC", Options.TEMPLATE_ANY_VALUE]
    CAMERA_PAIRING_RESPONSE = [b"CAMACK-HSEC", Options.TEMPLATE_ANY_VALUE, Options.TEMPLATE_ANY_VALUE]

    CAMERA_PAIR_REQUEST = [b"CAMLINK-HSEC", Options.TEMPLATE_ANY_VALUE]
    CAMERA_REPAIR_REQUEST = [b"CAMRELINK-HSEC", Options.TEMPLATE_ANY_VALUE]
    
    CAMERA_REPAIR_CONFIRM = [b"CAMREPAIR-HSEC"]
    CAMERA_REPAIR_CONFIRM_ACK = [b"CAMREPAIRACK-HSEC"]

    CAMERA_FRAME = [b"CAMFRAME-HSEC", Options.ANY_VALUE_ANY_LENGTH_TEMPLATE]
