from ..socket_server_lib.constants import Options

class Constants:
    DISCOVER_CAMERA_QUERY_PORT = 5000
    CAMERA_HANDLER_PORT = 5001
    SEPARATOR = b"\0"

    TEMPLATE_ANY_VALUE = b"\0"

    CAMERA_MAC_PREFIX = b"12:34:56"

class Messages:
    CAMERA_PAIRING_QUERY = [b"CAMPAIR-HSEC", Constants.TEMPLATE_ANY_VALUE]
    CAMERA_PAIRING_RESPONSE = [b"CAMACK-HSEC", Constants.TEMPLATE_ANY_VALUE, Constants.TEMPLATE_ANY_VALUE]

    CAMERA_PAIR_REQUEST = [b"CAMLINK-HSEC", Constants.TEMPLATE_ANY_VALUE]