SESSION_ID_VALIDITY_DURATION = 100000 # seconds
RESET_CODE_VALIDITY_DURATION = 300 # seconds
RED_ZONE_ALERT_COOLDOWN = 10 # seconds

JUMPSCARE = True
WATCH_UNTIL_JUMPSCARE = 1000
CHROMA_KEY_TOLERANCE = 75
JUMPSCARE_VIDEO = "assets/jumpscare2.mp4"
JUMPSACRE_CHROMA_KEY = "#359d3c"

class ResponseStatus:
    SUCCESS = "success"
    ERROR = "error"