from ..socket_server_lib.constants import Options

class Constants:
    CAMERA_HEARTBEAT_LISTENER_PORT = 5000
    CAMERA_HANDLER_PORT = 5001
    SERVER_COMMS_PORT = 5002

    CAMERA_MAC_PREFIX = "12:34:56"

    STATIC_CAMERA_FRAME_UPDATE_INTERVAL = 30
    
    RED_ZONE_SIMILARITY_THRESHOLD = 16
    FRAMES_BETWEEN_RED_ZONE_CHECKS = 20

class Messages:
    CAMERA_PAIRING_QUERY = [b"CAMPAIR-HSEC", Options.ANY_VALUE_TEMPLATE]
    CAMERA_PAIRING_RESPONSE = [b"CAMACK-HSEC", Options.ANY_VALUE_TEMPLATE, Options.ANY_VALUE_TEMPLATE]
    CAMERA_UNPAIR_REQUEST = [b"CAMUNPAIR-HSEC"]

    CAMERA_WRONG_CODE = [b"BADCODE-HSEC", Options.ANY_VALUE_TEMPLATE]

    CAMERA_PAIR_REQUEST = [b"CAMLINK-HSEC", Options.ANY_VALUE_TEMPLATE]
    CAMERA_REPAIR_REQUEST = [b"CAMRELINK-HSEC", Options.ANY_VALUE_TEMPLATE]
    
    CAMERA_REPAIR_CONFIRM = [b"CAMREPAIR-HSEC", Options.ANY_VALUE_TEMPLATE]
    CAMERA_REPAIR_CONFIRM_ACK = [b"CAMREPAIRACK-HSEC", Options.ANY_VALUE_TEMPLATE]

    CAMERA_FRAME = [b"CAMFRAME-HSEC", Options.ANY_VALUE_ANY_LENGTH_TEMPLATE]
